// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdvertiseBox: typeof import('./components/AdvertiseBox.vue')['default']
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppMenu: typeof import('./components/app/AppMenu.vue')['default']
    AppProfile: typeof import('./components/app/AppProfile.vue')['default']
    AppSubmenu: typeof import('./components/app/AppSubmenu.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    AtomPortal: typeof import('./components/Atoms/portal/AtomPortal.vue')['default']
    Button: typeof import('./components/Atoms/buttons/Button.vue')['default']
    'Button.story': typeof import('./components/Atoms/buttons/Button.story.vue')['default']
    Calendar: typeof import('./components/Molecules/Calendar.vue')['default']
    Checkbox: typeof import('./components/Atoms/checkbox/Checkbox.vue')['default']
    'Checkbox.story': typeof import('./components/Atoms/checkbox/Checkbox.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
